# Generated by Django 5.1.1 on 2024-11-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(choices=[('company1', 'Company 1'), ('company2', 'Company 2')], default='company1', max_length=10),
        ),
    ]
