# Generated by Django 5.1.1 on 2024-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.CharField(choices=[('company1', 'Company 1'), ('company2', 'Company 2')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(choices=[('company1', 'Company 1'), ('company2', 'Company 2')], max_length=10),
        ),
    ]
