# Generated by Django 5.1.1 on 2024-10-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
